server:
  port: 9091

security:
  user:
    name: api
    password: api

logging:
  file: logs/application.log

my:
  bucket: morse-coder-dev
  bucketUrl: https://s3.amazonaws.com/io.klerch.alexa.morse/
  bucketImgCodeFolder: img/codes
  bucketImgLiteralFolder: img/letters
  bucketMp3Folder: mp3
